
name: CI

on:
  push:
    branches: [ "Учительская" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install tree
        run: |
         #sudo apt-get install -y tree           
      - name: Array
        run: |
          branch_arr=("ПИН" "ИВТ" "КТ" "ИКТ" "ПМ" "РТ")
          #branch_arr=("ПИН")
          echo "point1"
          curr_sha=$(echo ${{ github.event.before }} | cut -c1-6)
          git log --pretty=format:"%h" | cut -c1-6 | sed '/'"$curr_sha"'/,$d' > tmp
          echo -e "current sha result: $curr_sha \n ------------"
          echo "tmp result: "
          cat tmp
          echo -e "end of tmp result \n\n"
          
          sha_arr=$(cat tmp)
          echo "point2"
          git fetch > 2
          echo "point3"
          for branch in "${branch_arr[@]}"; do
            echo "point3.5"
            git checkout $branch > 2
            git checkout Учительская > 2
            echo "point4"
            for sha in "${sha_arr[@]}"; do
              echo "/////Current SHA: $sha/////"
              file_arr=$(git diff --name-only $sha)
              echo "point5"
              echo -e "List of changed files: $(git diff --name-only $sha) \n---------\n\n"
              
              for file in "${file_arr[@]}"; do
                echo "/////Current file: $file/////"
                echo "point6"
                if [ -e $file ]
                then
                  echo "point 7"
                  echo "File $file in $branch branch will be update"
                else
                  echo "point 8"
                  echo "File $file not found in $branch branch"
                fi
              done
            done
            echo -e "End of $branch branch \n------------\n\n"
          done
          pwd
          #echo ${{ github.event.before }} | cut -c1-7 > tmp
          #git diff --name-only $(cat tmp)
          #echo "-----------"
          #git log --pretty=format:"%h" | cut -c1-7
          #echo '-----------------'
          #git log -5
          
