
name: CI

on:
  push:
    branches: [ "Учительская" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install tree
        run: |
         #sudo apt-get install -y tree           
      - name: Array
        run: |
          branch_arr=("ПИН", "ИВТ", "КТ", "ИКТ", "ПМ", "РТ")
          #branch_arr=("ПИН")
          
          curr_sha=${{ github.event.before }}
          git log --pretty=format:"%h" | cut -c1-7 | sed '/'"$curr_sha"'/,$d' > tmp
          sha_arr=$(cat tmp)
          
          git fetch > 2
          
          for branch in "${branch_arr[@]}"; do
            git checkout $branch > 2
            for sha in "${sha_arr[@]}"; do
              file_arr=(git diff --name-only $sha)
              for file in "${file arr[@]}"; do
                if [ -e $file ]
                then
                  echo "File $file in $branch branch will be update"
                else
                  echo "File $file not found in $branch branch"
                fi
              done
            done
          done
          pwd
          echo ${{ github.event.before }} | cut -c1-7 > tmp
          git diff --name-only $(cat tmp)
          echo "-----------"
          git log --pretty=format:"%h" | cut -c1-7
          echo '-----------------'
          git log -5
          
