
name: CI

on:
  push:
    branches: [ "Учительская" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install tree
        run: |
         # sudo apt-get install -y tree           
      - name: Array
        run: |
          arr=("ИБ" "ИВТ" "ИКТ" "КТ" "ПИН" "ПМ" "РТ" "Учительская")
          for i in ${arr[@]}; do
            echo "$i"
            git checkout ИБ
            
          done
          
          echo ---------
          #git diff  ИВТ:Лекции/Лекция 01.\ Вводная.md/  Учительская:lect-pm/le1-intro.md > tmp
          #wc -c tmp | awk '{print $1}'
          

