
name: CI

on:
  push:
    branches: [ "Учительская" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install tree
        run: |
         # sudo apt-get install -y tree           
      - name: Array
        run: |
          arr=("ИБ" "ИВТ" "ИКТ" "КТ" "ПИН" "ПМ" "РТ" "Учительская" "master")
          git fetch
          for i in ${arr[@]}; do
            git checkout $i > 2
            git diff $i:labs/labs-pin.md Учительская:README.md > tmp
            if [ "$(wc -c tmp | awk '{print $1}')" -gt 0 ]
            then
              echo "$i not equal Учительская"
            else 
              echo "$i good"
            fi
          done
          echo ---------
          

