
name: CI

on:
  push:
    branches: [ "Учительская" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install tree
        run: |
         #sudo apt-get install -y tree           
      - name: Array
        run: |
          arr=("ПИН" "Учительская")
          git fetch > 2
          for i in ${arr[@]}; do
            git checkout $i > 2
            git diff $i:labs/labs-pin.md Учительская:labs/labs-pin.md > tmp
            if [ "$(wc -c tmp | awk '{print $1}')" -gt 0 ]
            then
              echo "$i not equal Учительская"
              echo "do cherry pick"
            else 
              echo "$i good"
            fi  
          done
          pwd
          echo ${{ github.event.before }} | cut -c1-7 | git diff --name-only
          echo "-----------"
          git log --pretty=format:"%h" | cut -c1-7
          echo '-----------------'
          git log -5
          
