
name: CI

on:
  push:
    branches: [ "Учительская" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install tree
        run: |
          sudo apt-get install -y tree           
      - name: Tree
        run: |
          pwd
          ls -la 
          echo ---------
          tree
