
name: CI

on:
  push:
    branches: [ "Учительская" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install tree
        run: |
         # sudo apt-get install -y tree           
      - name: Array
        run: |
          arr=("ИБ" "ИВТ" "ИКТ" "КТ" "ПИН" "ПМ" "РТ" "Учительская")
          git fetch
          for i in ${arr[@]}; do
           echo "$i"
          git checkout $i  
          done
          echo ---------
          git diff ПИН:labs/labs-pin.md master:README.md > tmp
          wc -c tmp | awk '{print $1}'
          

